services:

  # -------------------------
  # SmartLogAnalytics API
  # -------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: smartloganalytics-app

    ports:
      - "5000:5000"

    env_file:
      - backend/.env

    environment:
      DB_HOST: 172.30.203.45
      MINIO_ENDPOINT: minio:9000

    depends_on:
      - minio

  # -------------------------
  # MinIO Object Storage
  # -------------------------
  minio:
    image: quay.io/minio/minio:latest

    container_name: smartloganalytics-minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    volumes:
      - minio_data:/data

    command: server /data --console-address ":9001"


volumes:
  minio_data: